### ISSUE TITLE
a question about the toolbox

### ISSUE THREAD

**Issue by JXXabc** [hazirbas/ddff-toolbox#2]
Hi ,
     When I read this paper, I found that you provided the experimental results of the 4D light field benchmark. I know that you generated its focus stack, so what I want to know is whether you get it through the toolbox and if the parameters are the same as DDFF-12.If they are different,would you please share the  focal stack of 4D light field benchmark or the parameters for generating it?

**Comment by hazirbas** [comment]
Hi,
yes we use the toolbox to generate the focal stacks.
